#!/bin/bash

npm un @papillonbits/library @papillonbits/setup @primer/primitives classnames graphql-request prop-types react react-dom react-redux react-router react-router-dom redux redux-logger redux-mock-store redux-thunk uuid whatwg-fetch

npm un @axe-core/react @babel/core @babel/eslint-parser @babel/plugin-proposal-class-properties @babel/plugin-proposal-nullish-coalescing-operator @babel/plugin-proposal-object-rest-spread @babel/plugin-proposal-optional-catch-binding @babel/plugin-proposal-optional-chaining @babel/plugin-syntax-dynamic-import @babel/plugin-transform-classes @babel/plugin-transform-react-jsx @babel/plugin-transform-runtime @babel/plugin-transform-spread @babel/preset-env @babel/preset-react @babel/register @babel/runtime @storybook/addon-a11y @storybook/addon-actions @storybook/addon-backgrounds @storybook/addon-controls @storybook/addon-docs @storybook/addon-jest @storybook/addon-postcss @storybook/addon-storysource @storybook/addon-viewport @storybook/addons @storybook/builder-webpack5 @storybook/manager-webpack5 @storybook/preset-scss @storybook/react @storybook/source-loader @storybook/theming @svgr/webpack @testing-library/react babel-core babel-jest babel-loader babel-plugin-css-modules-transform babel-plugin-syntax-async-functions babel-plugin-transform-assets clean-webpack-plugin codecov copy-webpack-plugin css-loader css-minimizer-webpack-plugin dotenv dotenv-cli dotenv-webpack eslint eslint-config-airbnb eslint-config-prettier eslint-import-resolver-alias eslint-plugin-import eslint-plugin-jest eslint-plugin-jsx-a11y eslint-plugin-prettier eslint-plugin-react eslint-plugin-react-hooks file-loader gh-pages html-loader html-webpack-plugin husky identity-obj-proxy jest jest-axe jsdom jsdom-global lerna lint-staged markdown-loader mini-css-extract-plugin nodemon npm-run-all postcss postcss-loader postcss-preset-env postcss-scss prettier regenerator-runtime sass sass-loader style-loader stylelint stylelint-config-prettier stylelint-config-standard stylelint-order stylelint-prettier stylelint-scss url-loader webpack webpack-bundle-analyzer webpack-cli webpack-dev-server webpack-manifest-plugin

npm i -S @papillonbits/library @papillonbits/setup @primer/primitives classnames graphql-request prop-types react react-dom react-redux react-router react-router-dom redux redux-logger redux-mock-store redux-thunk uuid whatwg-fetch

npm i -D @axe-core/react @babel/core @babel/eslint-parser @babel/plugin-proposal-class-properties @babel/plugin-proposal-nullish-coalescing-operator @babel/plugin-proposal-object-rest-spread @babel/plugin-proposal-optional-catch-binding @babel/plugin-proposal-optional-chaining @babel/plugin-syntax-dynamic-import @babel/plugin-transform-classes @babel/plugin-transform-react-jsx @babel/plugin-transform-runtime @babel/plugin-transform-spread @babel/preset-env @babel/preset-react @babel/register @babel/runtime @storybook/addon-a11y @storybook/addon-actions @storybook/addon-backgrounds @storybook/addon-controls @storybook/addon-docs @storybook/addon-jest @storybook/addon-postcss @storybook/addon-storysource @storybook/addon-viewport @storybook/addons @storybook/builder-webpack5 @storybook/manager-webpack5 @storybook/preset-scss @storybook/react @storybook/source-loader @storybook/theming @svgr/webpack @testing-library/react babel-core@^7.0.0-bridge.0 babel-jest babel-loader babel-plugin-css-modules-transform babel-plugin-syntax-async-functions babel-plugin-transform-assets clean-webpack-plugin codecov copy-webpack-plugin css-loader css-minimizer-webpack-plugin dotenv dotenv-cli dotenv-webpack eslint eslint-config-airbnb eslint-config-prettier eslint-import-resolver-alias eslint-plugin-import eslint-plugin-jest eslint-plugin-jsx-a11y eslint-plugin-prettier eslint-plugin-react eslint-plugin-react-hooks file-loader gh-pages html-loader html-webpack-plugin husky identity-obj-proxy jest jest-axe jsdom jsdom-global lerna lint-staged markdown-loader mini-css-extract-plugin nodemon npm-run-all postcss postcss-loader postcss-preset-env postcss-scss prettier regenerator-runtime sass sass-loader style-loader stylelint stylelint-config-prettier stylelint-config-standard stylelint-order stylelint-prettier stylelint-scss url-loader webpack webpack-bundle-analyzer webpack-cli webpack-dev-server webpack-manifest-plugin

npm run clean-up && npm run install-packages && npm run bootstrap-release
